import 'package:flutter/material.dart';

import '../exercise/curl_up/curl_up.dart';
import '../exercise/exercise_base.dart';
import '../exercise/glute bridge/glute_bridge.dart';
import '../exercise/jumping jack/jumping_jack.dart';
import '../exercise/plank/plank.dart';
import '../exercise/lunge/lunge.dart';
import '../exercise/push up/push_up.dart';
import '../exercise/squat/squat.dart';
import '../exercise/butterfly_stretch/butterfly_stretch.dart';
import '../exercise/Sphinx_Pose/sphinx_stretch.dart';
import '../exercise/seated_forward_fold/seated_forward_fold.dart';

import '../exercise/1.Bird Dog/bird_dog.dart';
import '../exercise/2.Sit-Up/sit_up.dart';
import '../exercise/3.High Plank/high_plank.dart';
import '../exercise/4.Mountain Climber/mountain_climber.dart';
import '../exercise/5.Superman/superman.dart';
import '../exercise/7.Plank Shoulder Tap/plank_shoulder_tap.dart';
import '../exercise/8.Leg Raises (Supine)/leg_raise.dart';
import '../exercise/9.Reverse Crunch/reverse_crunch.dart';
import '../exercise/10.Vup/v_up.dart';
import '../exercise/12.Dead Bug/dead_bug.dart';
import '../exercise/13.Plank Up-Down/plank_up_down.dart';
import '../exercise/14.Bear Plank/bear_plank.dart';

import '../exercise/cossack_squat/cossack_squat.dart';
import '../exercise/walking_lunge/walking_lunge.dart';
import '../exercise/tricep_dip/tricep_dip.dart';
import '../exercise/russian_twist/russian_twist.dart';
import '../exercise/standing_knee_to_elbow/standing_knee_to_elbow.dart';
import '../exercise/Jump_Squat/jump_squat.dart';
import '../exercise/bow_pose/bow_pose.dart';
import '../exercise/side_plank_dip/side_plank_dip.dart';
import '../exercise/step_back_burpee/step_back_burpee.dart';
// import '../exercise/suryanamaskar/suryanamaskar.dart';
import '../exercise/pranamasana/pranamasana.dart';
import '../exercise/hasta_uttanasana/hasta_uttanasana.dart';
import '../exercise/hastapaadasana/hastapaadasana.dart';
import '../exercise/ashwa_sanchalanasana/ashwa_sanchalanasana.dart';
import '../exercise/parvatasana/parvatasana.dart';
import '../exercise/ashtanga_namaskara/ashtanga_namaskara.dart';

/* =========================================================================
   ExerciseDefinition — Metadata + factory for each exercise type.

   To add a new exercise:
   1. Create the exercise class extending ExerciseBase
   2. Add a new ExerciseDefinition entry to [exerciseDefinitions]
   3. Done — the HomeScreen and exercise flow will pick it up
   ========================================================================= */

class ExerciseDefinition {
  final String id;
  final String name;
  final String subtitle;
  final String description;
  final IconData icon;
  final Color primaryColor;
  final Color secondaryColor;
  final String difficulty;
  final List<String> targetMuscles;
  final String duration;
  final String cameraHint;
  final String framingHint;
  final List<String> setupTips;
  final ExerciseBase Function() createExercise;

  /// Optional safety warning shown prominently before exercise starts.
  final String? safetyWarning;

  /// Maps phaseKey → Color for the state pill during activated state.
  final Map<String, Color> phaseColors;

  const ExerciseDefinition({
    required this.id,
    required this.name,
    required this.subtitle,
    required this.description,
    required this.icon,
    required this.primaryColor,
    required this.secondaryColor,
    required this.difficulty,
    required this.targetMuscles,
    required this.duration,
    required this.cameraHint,
    required this.framingHint,
    required this.setupTips,
    required this.createExercise,
    this.safetyWarning,
    required this.phaseColors,
  });
}

/* =========================================================================
   EXERCISE REGISTRY — Add new exercises here.
   ========================================================================= */

/// ------------------ 5-rep for onboarding assessment. ------------------
/// Squat
final squatAssessmentDefinition = ExerciseDefinition(
  id: 'squat_assessment',
  name: 'Squat Assessment',
  subtitle: 'Kiểm tra tư thế Squat',
  description: '5 squats để AI đánh giá thể lực của bạn.',
  icon: Icons.fitness_center,
  primaryColor: const Color(0xFF00E5FF),
  secondaryColor: const Color(0xFF0091EA),
  difficulty: 'Dễ',
  targetMuscles: ['Đùi', 'Mông', 'Core'],
  duration: '5 reps',
  cameraHint: 'Đứng nghiêng người so với camera.',
  framingHint: 'Giữ vai, hông, gối, mắt cá và bàn chân trong khung hình.',
  setupTips: [
    'Đặt camera ngang hông, cách bạn khoảng 2–3 mét.',
    'Quay nghiêng 90° để AI thấy rõ độ sâu và thân người.',
    'Giữ đủ ánh sáng ở chân và thân trên trước khi bắt đầu.',
  ],
  createExercise: () => Squat(maxRep: 5),
  phaseColors: {
    'standing': const Color(0xFF00E676),
    'descending': const Color(0xFFFFD600),
    'bottom': const Color(0xFFFF6D00),
    'ascending': const Color(0xFF00B0FF),
  },
);

/// Wall- push up
final wallPushupAssessmentDefinition = ExerciseDefinition(
  id: 'wall_pushup_assessment',
  name: 'Wall Pushup Assessment',
  subtitle: 'Kiểm tra tư thế Wall Pushup',
  description: '5 wall pushups để AI đánh giá thể lực của bạn.',
  icon: Icons.fitness_center,
  primaryColor: const Color(0xFF00E5FF),
  secondaryColor: const Color(0xFF0091EA),
  difficulty: 'Dễ',
  targetMuscles: ['Ngực', 'Vai', 'Core'],
  duration: '5 reps',
  cameraHint: 'Đứng nghiêng người so với camera.',
  framingHint: 'Giữ vai, hông, gối, mắt cá và bàn chân trong khung hình.',
  setupTips: [
    'Đặt camera ngang hông, cách bạn khoảng 2–3 mét.',
    'Quay nghiêng 90° để AI thấy rõ độ sâu và thân người.',
    'Giữ đủ ánh sáng ở chân và thân trên trước khi bắt đầu.',
  ],
  createExercise: () => PushUp(maxRep: 5),
  phaseColors: {
    'standing': const Color(0xFF00E676),
    'descending': const Color(0xFFFFD600),
    'bottom': const Color(0xFFFF6D00),
    'ascending': const Color(0xFF00B0FF),
  },
);
final List<ExerciseDefinition> exerciseDefinitions = [
  ExerciseDefinition(
    id: 'squat',
    name: 'Squat',
    subtitle: 'Phân tích tư thế Squat',
    description:
        'AI phân tích form squat theo thời gian thực.\nTheo dõi độ sâu, thân trên, nhịp và nhiều hơn.',
    icon: Icons.fitness_center,
    primaryColor: const Color(0xFF00E5FF),
    secondaryColor: const Color(0xFF0091EA),
    difficulty: 'Trung bình',
    targetMuscles: ['Đùi', 'Mông', 'Core'],
    duration: '15 reps',
    cameraHint: 'Đứng nghiêng người so với camera.',
    framingHint: 'Giữ vai, hông, gối, mắt cá và bàn chân trong khung hình.',
    setupTips: [
      'Đặt camera ngang hông, cách bạn khoảng 2–3 mét.',
      'Quay nghiêng 90° để AI thấy rõ độ sâu và thân người.',
      'Giữ đủ ánh sáng ở chân và thân trên trước khi bắt đầu.',
    ],
    createExercise: () => Squat(),
    phaseColors: {
      'standing': const Color(0xFF00E676),
      'descending': const Color(0xFFFFD600),
      'bottom': const Color(0xFFFF6D00),
      'ascending': const Color(0xFF00B0FF),
    },
  ),
  ExerciseDefinition(
    id: 'plank',
    name: 'Plank',
    subtitle: 'McGill Short-Hold Protocol',
    description:
        '3 lần giữ × 10 giây mỗi lần.\nPhân tích thân trên, cổ và đầu gối theo thời gian thực.',
    icon: Icons.self_improvement,
    primaryColor: const Color(0xFFFF9800),
    secondaryColor: const Color(0xFFE65100),
    difficulty: 'Dễ – Trung bình',
    targetMuscles: ['Core', 'Vai', 'Lưng'],
    duration: '3 × 10s',
    cameraHint: 'Quay nghiêng người so với camera.',
    framingHint: 'Ưu tiên thấy rõ vai, hông, tai và đầu gối.',
    setupTips: [
      'Đặt điện thoại thấp ngang thân người để thấy rõ thân plank.',
      'Giữ phần thân trên sáng và không che khuất vai/hông.',
      'Nếu không đủ chỗ, vẫn cố gắng giữ đầu gối và mông trọn khung.',
    ],
    createExercise: () => Plank(),
    phaseColors: {
      'setup': const Color(0xFFFF9800),
      'holding': const Color(0xFF00E676),
      'resting': const Color(0xFF29B6F6),
    },
  ),
  ExerciseDefinition(
    id: 'lunge',
    name: 'Lunge',
    subtitle: 'Phân tích tư thế Lunge',
    description:
        'AI phân tích form lunge theo thời gian thực.\nTheo dõi độ sâu, đầu gối, gót chân và thân trên.',
    icon: Icons.directions_walk,
    primaryColor: const Color(0xFF7C4DFF),
    secondaryColor: const Color(0xFF6200EA),
    difficulty: 'Trung bình',
    targetMuscles: ['Đùi', 'Mông', 'Hamstring'],
    duration: '10 reps',
    cameraHint: 'Quay nghiêng người so với camera.',
    framingHint: 'Giữ vai, hông, gối và bàn chân trong khung hình.',
    setupTips: [
      'Đặt camera ngang hông, cách bạn khoảng 2–3 mét.',
      'Quay nghiêng 90° để AI thấy rõ độ sâu đầu gối.',
      'Giữ đủ ánh sáng ở chân và thân trên trước khi bắt đầu.',
    ],
    createExercise: () => Lunge(),
    phaseColors: {
      'standing': const Color(0xFF00E676),
      'descending': const Color(0xFFFFD600),
      'bottom': const Color(0xFFFF6D00),
      'ascending': const Color(0xFF00B0FF),
    },
  ),
  ExerciseDefinition(
    id: 'jumping_jack',
    name: 'Jumping Jack',
    subtitle: 'Cardio nhẹ cho dân văn phòng',
    description:
        'AI phân tích tư thế nhảy dạng.\nTheo dõi tay, chân và nhịp độ.',
    icon: Icons.directions_run,
    primaryColor: const Color(0xFF76FF03),
    secondaryColor: const Color(0xFF64DD17),
    difficulty: 'Dễ',
    targetMuscles: ['Toàn thân', 'Vai', 'Chân'],
    duration: '30 reps',
    cameraHint: 'Đứng đối diện camera.',
    framingHint: 'Giữ toàn thân, hai tay và hai chân luôn ở trong khung hình.',
    setupTips: [
      'Lùi xa camera để khi dang tay và chân vẫn không bị cắt khung.',
      'Giữ đầu, cổ tay và mắt cá luôn nhìn thấy rõ.',
      'Chừa khoảng trống phía trên đầu vì tay sẽ vươn cao qua đầu.',
    ],
    createExercise: () => JumpingJack(),
    phaseColors: {
      'closed': const Color(0xFF00E676),
      'open': const Color(0xFFFFD600),
    },
  ),
  ExerciseDefinition(
    id: 'push_up',
    name: 'Push Up',
    subtitle: 'Theo dõi độ sâu và thân người',
    description:
        'AI phân tích chống đẩy theo thời gian thực.\nTheo dõi thân người, độ sâu và nhịp độ.',
    icon: Icons.sports_gymnastics,
    primaryColor: const Color(0xFFFF6E40),
    secondaryColor: const Color(0xFFFF3D00),
    difficulty: 'Trung bình',
    targetMuscles: ['Ngực', 'Vai', 'Core'],
    duration: '15 reps',
    cameraHint: 'Quay nghiêng người so với camera.',
    framingHint: 'Giữ vai, khuỷu tay, cổ tay và hông luôn trong khung hình.',
    setupTips: [
      'Đặt camera thấp ngang thân để thấy rõ đường vai–hông.',
      'Giữ thân trên và khuỷu tay đủ sáng trước khi bắt đầu.',
      'Lùi camera thêm nếu cổ tay hoặc đầu dễ bị cắt khung.',
    ],
    createExercise: () => PushUp(),
    phaseColors: {
      'plank': const Color(0xFF00E676),
      'descending': const Color(0xFFFFD600),
      'bottom': const Color(0xFFFF6D00),
      'ascending': const Color(0xFFFF6E40),
    },
  ),
  ExerciseDefinition(
    id: 'glute_bridge',
    name: 'Glute Bridge',
    subtitle: 'Kích hoạt mông và lưng dưới',
    description:
        'AI phân tích tư thế cầu mông theo thời gian thực.\nTheo dõi độ nâng hông, giữ đỉnh và nhịp độ hạ xuống.',
    icon: Icons.airline_seat_flat,
    primaryColor: const Color(0xFFE040FB),
    secondaryColor: const Color(0xFF7B1FA2),
    difficulty: 'Dễ – Trung bình',
    targetMuscles: ['Mông', 'Hamstring', 'Lưng dưới'],
    duration: '15 reps',
    cameraHint: 'Quay nghiêng người so với camera.',
    framingHint: 'Giữ vai, hông, gối và bàn chân luôn trong khung hình.',
    setupTips: [
      'Đặt camera thấp ngang thân (khoảng 30–50 cm so với mặt sàn).',
      'Quay nghiêng 90° để AI thấy rõ chuyển động hông.',
      'Đảm bảo đủ ánh sáng dọc theo thân người trước khi bắt đầu.',
    ],
    createExercise: () => GluteBridge(),
    phaseColors: {
      'bottom': const Color(0xFF00E676),
      'ascending': const Color(0xFFFFD600),
      'topHold': const Color(0xFFE040FB),
      'descending': const Color(0xFF00B0FF),
    },
  ),
  ExerciseDefinition(
    id: 'curl_up',
    name: 'McGill Curl-up',
    subtitle: 'Core on dinh va gap than co kiem soat',
    description:
        'AI theo doi bai curl-up theo thoi gian thuc.\nTap trung vao goc gap than, co va dau goi.',
    icon: Icons.accessibility_new_rounded,
    primaryColor: const Color(0xFF26A69A),
    secondaryColor: const Color(0xFF00695C),
    difficulty: 'De - Trung binh',
    targetMuscles: ['Core', 'Bung truoc', 'Hong'],
    duration: '12 reps',
    cameraHint: 'Quay nghieng nguoi so voi camera.',
    framingHint: 'Giu vai, hong, dau goi va tai trong khung hinh.',
    setupTips: [
      'Dat camera thap ngang than de thay ro duong vai-hong.',
      'Giu dau, vai va dau goi du sang truoc khi bat dau.',
      'Nam ngang tren san, gap mot dau goi theo dung tu the McGill.',
    ],
    createExercise: () => CurlUp(maxRep: 12),
    phaseColors: {
      'resting': const Color(0xFF00E676),
      'ascending': const Color(0xFFFFD600),
      'descending': const Color(0xFF00B0FF),
    },
  ),

ExerciseDefinition(
    id: 'butterfly_stretch',
    name: 'Butterfly Stretch',
    subtitle: 'Ep deo khop hang',
    description: 'Gian co khep hong, giam cang thang that lung.\nTap trung vao khoang cach 2 goi va tu the lung.',
    icon: Icons.accessibility_new_rounded,
    primaryColor: const Color(0xFF2B5EA6),
    secondaryColor: const Color(0xFF5CEAA8),
    difficulty: 'Co ban',
    targetMuscles: ['Hong', 'Dui trong', 'Lung duoi'],
    duration: '30s',
    cameraHint: 'Dat dien thoai chinh dien.',
    framingHint: 'Dam bao thay toan bo co the tu dau den chan.',
    setupTips: [
      'Ngoi thang, vuon cao cot song.',
      'Hai long ban chan ap sat vao nhau.',
      'Tu tu ep hai dau goi huong xuong san.',
    ],
    createExercise: () => ButterflyStretch(),
    phaseColors: {
      'setup': const Color(0xFF97958D),
      'stretching': const Color(0xFFB87320),
      'isometric_hold': const Color(0xFF1B6B52),
      'release': const Color(0xFF2B5EA6),
    },
  ),
ExerciseDefinition(
  id: 'sphinx_pose',
  name: 'Sphinx Pose',
  subtitle: 'Tư thế nhân sư - Trị liệu cột sống',
  description: 'Bài tập kéo giãn tĩnh giúp giảm áp lực đĩa đệm, giải tỏa căng thẳng vùng thắt lưng và định tuyến lại cột sống.', // <--- Đã thêm
  icon: Icons.self_improvement_rounded,
  primaryColor: const Color(0xFFCBB8F0),
  secondaryColor: const Color(0xFF9575CD),
  cameraHint: 'Quay ngang hông (Side View)',
  framingHint: 'Đảm bảo thấy rõ từ vai đến mũi chân',
  duration: '30s - 1m',
  difficulty: 'Cơ bản',
  targetMuscles: const ['Lưng dưới', 'Cột sống', 'Core'],
  setupTips: const [
    'Nằm sấp hoàn toàn trên thảm',
    'Tỳ cẳng tay xuống sàn, cùi chỏ dưới vai',
    'Hít sâu, từ từ nâng ngực lên, vươn dài cổ'
  ],
  safetyWarning: 'Không ngửa cổ quá gắt. Dừng lại ngay nếu thấy đau nhói ở thắt lưng.',
  phaseColors: const { // <--- Đã thêm Map màu cho UI Bridge
    'proneSetup': Colors.grey,
    'ascending': Color(0xFF29B6F6),
    'isometricHold': Color(0xFF00E676),
    'descending': Color(0xFFFF9800),
  },
  createExercise: () => SphinxStretch(), 
),
ExerciseDefinition(
    id: 'seated_forward_fold',
    name: 'Seated Forward Fold',
    subtitle: 'Kéo giãn gân kheo và cột sống',
    difficulty: 'Cơ bản',
    duration: '2 phút',
    description: 'Bài tập kéo giãn tĩnh giúp tăng độ dẻo dai cho cơ gân kheo và cột sống. Rất tốt cho người làm việc văn phòng cần nới lỏng cơ bắp.',
    targetMuscles: const ['Gân kheo', 'Lưng dưới'],
    cameraHint: 'Đặt điện thoại quay ngang người (Side View), để lộ rõ từ vai đến bàn chân.',
    framingHint: 'Đảm bảo toàn thân từ đầu đến gót chân nằm gọn trong khung hình.',
    setupTips: const [
      'Ngồi thẳng lưng trên thảm, hai chân duỗi thẳng ép sát sàn.',
      'Gập người bắt nguồn từ khớp hông (hip hinge), đẩy ngực về phía trước mũi chân.',
      'Bẻ gập mũi chân hướng lên trần nhà để tăng hiệu quả kéo giãn.',
    ],
    phaseColors: const {
      'setup': Color(0xFFFF9800),         // Amber (Chuẩn bị)
      'descending': Color(0xFF2B5EA6),    // Blue (Gập người)
      'isometricHold': Color(0xFF1B6B52), // Jade (Giữ tĩnh)
      'ascending': Color(0xFF7040B8),     // Purple (Nhả cơ)
    },
    icon: Icons.accessibility_new_rounded,
    primaryColor: const Color(0xFF2B5EA6), // VFTheme.blue
    secondaryColor: const Color(0xFF00E5FF),
    createExercise: () => SeatedForwardFold(),
  ),
  ExerciseDefinition(
    id: 'bird_dog',
    name: 'Bird Dog',
    subtitle: 'Tăng cường core & thăng bằng',
    description: 'Bài tập Bird Dog giúp tăng sức mạnh lõi và thăng bằng.',
    icon: Icons.accessibility_new,
    primaryColor: const Color(0xFF4CAF50),
    secondaryColor: const Color(0xFF388E3C),
    difficulty: 'Cơ bản',
    targetMuscles: const ['Core', 'Lưng dưới', 'Mông'],
    duration: '10 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Đảm bảo thấy toàn thân.',
    setupTips: const ['Vào tư thế cái bàn', 'Giữ lưng phẳng'],
    createExercise: () => BirdDog(),
    phaseColors: const { 'setup': Colors.grey, 'extending': Colors.blue, 'hold': Colors.green, 'returning': Colors.orange },
  ),
  ExerciseDefinition(
    id: 'sit_up',
    name: 'Sit-Up',
    subtitle: 'Gập bụng cơ bản',
    description: 'Phát triển sức mạnh cơ bụng toàn diện.',
    icon: Icons.fitness_center,
    primaryColor: const Color(0xFFE91E63),
    secondaryColor: const Color(0xFFC2185B),
    difficulty: 'Trung bình',
    targetMuscles: const ['Cơ bụng'],
    duration: '15 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Thấy rõ từ đầu đến chân.',
    setupTips: const ['Nằm ngửa, gập gối', 'Hai tay để hờ sau gáy'],
    createExercise: () => SitUp(),
    phaseColors: const { 'lying': Colors.grey, 'curling': Colors.orange, 'top': Colors.green, 'lowering': Colors.blue },
  ),
  ExerciseDefinition(
    id: 'high_plank',
    name: 'High Plank',
    subtitle: 'Plank cao tay',
    description: 'Bài tập chống đẩy tĩnh giúp tăng cường toàn thân.',
    icon: Icons.horizontal_rule,
    primaryColor: const Color(0xFFFF9800),
    secondaryColor: const Color(0xFFF57C00),
    difficulty: 'Cơ bản',
    targetMuscles: const ['Core', 'Vai', 'Ngực'],
    duration: '60s',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Đảm bảo thấy toàn bộ cơ thể từ đầu đến gót chân.',
    setupTips: const ['Chống tay thẳng đứng', 'Giữ lưng phẳng'],
    createExercise: () => HighPlank(),
    phaseColors: const { 'setup': Colors.grey, 'holding': Colors.green },
  ),
  ExerciseDefinition(
    id: 'mountain_climber',
    name: 'Mountain Climber',
    subtitle: 'Cardio & Core',
    description: 'Bài tập leo núi kết hợp cardio và tăng cường core.',
    icon: Icons.directions_run,
    primaryColor: const Color(0xFFF44336),
    secondaryColor: const Color(0xFFD32F2F),
    difficulty: 'Trung bình',
    targetMuscles: const ['Core', 'Chân', 'Vai'],
    duration: '20 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Thấy rõ toàn thân.',
    setupTips: const ['Bắt đầu ở High Plank', 'Co từng gối về phía ngực'],
    createExercise: () => MountainClimber(),
    phaseColors: const { 'setup': Colors.grey, 'active': Colors.green },
  ),
  ExerciseDefinition(
    id: 'superman',
    name: 'Superman',
    subtitle: 'Tăng cường lưng dưới',
    description: 'Bài tập tư thế siêu nhân giúp làm khoẻ cơ lưng dưới.',
    icon: Icons.flight,
    primaryColor: const Color(0xFF2196F3),
    secondaryColor: const Color(0xFF1976D2),
    difficulty: 'Cơ bản',
    targetMuscles: const ['Lưng dưới', 'Mông', 'Lưng giữa'],
    duration: '10 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Thấy toàn thân nằm trên thảm.',
    setupTips: const ['Nằm sấp', 'Duỗi thẳng tay và chân'],
    createExercise: () => Superman(),
    phaseColors: const { 'setup': Colors.grey, 'lifting': Colors.orange, 'hold': Colors.green, 'lowering': Colors.blue },
  ),
  ExerciseDefinition(
    id: 'plank_shoulder_tap',
    name: 'Plank Shoulder Tap',
    subtitle: 'Chạm vai tư thế plank',
    description: 'Rèn luyện khả năng chống xoay của core.',
    icon: Icons.touch_app,
    primaryColor: const Color(0xFF00BCD4),
    secondaryColor: const Color(0xFF0097A7),
    difficulty: 'Trung bình',
    targetMuscles: const ['Core', 'Vai'],
    duration: '20 reps',
    cameraHint: 'Quay ngang người (Side View) hoặc hơi chếch.',
    framingHint: 'Thấy tay và vai.',
    setupTips: const ['High Plank', 'Mở rộng hai chân để giữ thăng bằng'],
    createExercise: () => PlankShoulderTap(),
    phaseColors: const { 'plank': Colors.grey, 'tapping_left': Colors.blue, 'tapping_right': Colors.orange },
  ),
  ExerciseDefinition(
    id: 'leg_raise',
    name: 'Leg Raises (Supine)',
    subtitle: 'Nâng chân bụng dưới',
    description: 'Phát triển vùng cơ bụng dưới.',
    icon: Icons.airline_seat_flat,
    primaryColor: const Color(0xFF3F51B5),
    secondaryColor: const Color(0xFF303F9F),
    difficulty: 'Trung bình',
    targetMuscles: const ['Bụng dưới', 'Hông'],
    duration: '15 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Thấy toàn bộ thân và chân.',
    setupTips: const ['Nằm ngửa', 'Giữ thắt lưng sát sàn'],
    createExercise: () => LegRaise(),
    phaseColors: const { 'lying': Colors.grey, 'raising': Colors.orange, 'top': Colors.green, 'lowering': Colors.blue },
  ),
  ExerciseDefinition(
    id: 'reverse_crunch',
    name: 'Reverse Crunch',
    subtitle: 'Gập bụng ngược',
    description: 'Tập trung cơ bụng dưới bằng cách cuộn khung chậu.',
    icon: Icons.sync,
    primaryColor: const Color(0xFF9C27B0),
    secondaryColor: const Color(0xFF7B1FA2),
    difficulty: 'Khó',
    targetMuscles: const ['Bụng dưới', 'Core'],
    duration: '15 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Thấy rõ vùng hông và đùi.',
    setupTips: const ['Co gối 90 độ', 'Cuộn xương chậu nâng hông lên'],
    createExercise: () => ReverseCrunch(),
    phaseColors: const { 'setup': Colors.grey, 'curling': Colors.orange, 'top': Colors.green, 'lowering': Colors.blue },
  ),
  ExerciseDefinition(
    id: 'v_up',
    name: 'V-Up',
    subtitle: 'Gập bụng chữ V',
    description: 'Bài gập bụng nâng cao đòi hỏi sức mạnh và thăng bằng.',
    icon: Icons.change_history,
    primaryColor: const Color(0xFFFFC107),
    secondaryColor: const Color(0xFFFFA000),
    difficulty: 'Khó',
    targetMuscles: const ['Toàn bộ bụng'],
    duration: '12 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Thấy được mũi tay chạm mũi chân.',
    setupTips: const ['Duỗi thẳng tay chân', 'Gập đồng thời thân và chân'],
    createExercise: () => VUp(),
    phaseColors: const { 'lying': Colors.grey, 'folding': Colors.orange, 'vShape': Colors.green, 'unfolding': Colors.blue },
  ),

  ExerciseDefinition(
    id: 'dead_bug',
    name: 'Dead Bug',
    subtitle: 'Bọ chết',
    description: 'Rèn luyện khả năng điều khiển thân chéo.',
    icon: Icons.bug_report,
    primaryColor: const Color(0xFF795548),
    secondaryColor: const Color(0xFF5D4037),
    difficulty: 'Trung bình',
    targetMuscles: const ['Core', 'Khung chậu'],
    duration: '20 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Thấy rõ 4 chi di chuyển.',
    setupTips: const ['Co gối 90 độ, tay thẳng vuông góc', 'Hạ tay và chân đối diện'],
    createExercise: () => DeadBug(),
    phaseColors: const { 'setup': Colors.grey, 'extending': Colors.blue, 'hold': Colors.green, 'returning': Colors.orange },
  ),
  ExerciseDefinition(
    id: 'plank_up_down',
    name: 'Plank Up-Down',
    subtitle: 'Chuyển đổi High-Low Plank',
    description: 'Tăng cường sức mạnh vai và core.',
    icon: Icons.swap_vert,
    primaryColor: const Color(0xFF607D8B),
    secondaryColor: const Color(0xFF455A64),
    difficulty: 'Khó',
    targetMuscles: const ['Core', 'Vai', 'Ngực'],
    duration: '10 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Thấy rõ tay chống đẩy.',
    setupTips: const ['Bắt đầu bằng Plank thấp', 'Lên từng tay một'],
    createExercise: () => PlankUpDown(),
    phaseColors: const { 'highPlank': Colors.green, 'lowPlank': Colors.blue, 'transitioning': Colors.orange },
  ),
  ExerciseDefinition(
    id: 'bear_plank',
    name: 'Bear Plank',
    subtitle: 'Plank tư thế gấu',
    description: 'Chống mỏi đùi trước và sức mạnh tĩnh core.',
    icon: Icons.pets,
    primaryColor: const Color(0xFF8D6E63),
    secondaryColor: const Color(0xFF6D4C41),
    difficulty: 'Trung bình',
    targetMuscles: const ['Core', 'Đùi trước', 'Vai'],
    duration: '45s',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Thấy rõ khoảng cách gối và mặt sàn.',
    setupTips: const ['Tư thế cái bàn', 'Nâng gối cách sàn 5-10cm'],
    createExercise: () => BearPlank(),
    phaseColors: const { 'setup': Colors.grey, 'hovering': Colors.green, 'fatiguing': Colors.red },
  ),
  // ExerciseDefinition(
  //   id: 'suryanamaskar',
  //   name: 'Chào mặt trời',
  //   subtitle: 'Chuỗi Chào Mặt Trời 12 bước',
  //   description: 'Chuỗi 12 tư thế Yoga liên hoàn giúp kích hoạt toàn thân, tăng độ dẻo dai cột sống và cải thiện nhịp thở.\nMỗi vòng đi qua 12 trạm từ Cầu nguyện → Rắn hổ mang → trở về.',
  //   icon: Icons.self_improvement,
  //   primaryColor: const Color(0xFFFF8A65),
  //   secondaryColor: const Color(0xFFFF5722),
  //   difficulty: 'Trung bình',
  //   targetMuscles: const ['Toàn thân', 'Cột sống', 'Core', 'Chân'],
  //   duration: '5 vòng',
  //   cameraHint: 'Quay ngang người 100% (Side View).',
  //   framingHint: 'Đảm bảo thấy toàn thân từ đầu đến chân, chừa khoảng trống khi nằm sấp.',
  //   setupTips: const [
  //     'Đặt camera quay ngang, cách bạn 3–4 mét để thấy toàn thân khi nằm.',
  //     'Trải thảm yoga theo chiều dài hướng camera.',
  //     'Hít thở sâu, bắt đầu ở tư thế đứng thẳng tay chắp trước ngực.',
  //   ],
  //   safetyWarning: 'Không gượng ép nếu đau lưng. Dừng lại ngay nếu chóng mặt.',
  //   // createExercise: () => Suryanamaskar(),
  //   phaseColors: const {
  //     'p1_pranamasana': Color(0xFF00E676),
  //     'p2_hasta_uttanasana': Color(0xFFFFD600),
  //     'p3_hastapaadasana': Color(0xFFFF9800),
  //     'p4_ashwa_sanchalanasana': Color(0xFFFF6D00),
  //     'p5_parvatasana': Color(0xFF2196F3),
  //     'p6_ashtanga_namaskara': Color(0xFFE91E63),
  //     'p7_bhujangasana': Color(0xFF9C27B0),
  //     'p8_parvatasana_return': Color(0xFF2196F3),
  //     'p9_ashwa_return': Color(0xFFFF6D00),
  //     'p10_hastapaadasana_return': Color(0xFFFF9800),
  //     'p11_hasta_uttanasana_return': Color(0xFFFFD600),
  //     'p12_pranamasana_return': Color(0xFF00E676),
  //   },
  // ),
  ExerciseDefinition(
    id: 'cossack_squat',
    name: 'Cossack Squat',
    subtitle: 'Tăng cường sức mạnh và độ linh hoạt cho hông/đùi',
    description: 'Squat sang một bên luân phiên. Cải thiện độ dẻo dai cơ đùi trong và sức mạnh chân trụ.',
    icon: Icons.fitness_center,
    primaryColor: const Color(0xFFE91E63),
    secondaryColor: const Color(0xFFC2185B),
    difficulty: 'Khó',
    targetMuscles: const ['Đùi', 'Mông', 'Hông'],
    duration: '16 reps',
    cameraHint: 'Quay chính diện (Front View).',
    framingHint: 'Đảm bảo thấy toàn bộ cơ thể từ đầu đến chân.',
    setupTips: const [
      'Đứng dang chân rộng gấp 1.5 - 2 lần vai.',
      'Giữ lưng thẳng, mũi chân hơi hướng ra ngoài.',
    ],
    createExercise: () => CossackSquat(),
    phaseColors: const { 'standing': Colors.green, 'descending': Colors.orange, 'bottom': Colors.red, 'ascending': Colors.blue },
  ),
  ExerciseDefinition(
    id: 'walking_lunge',
    name: 'Walking Lunge',
    subtitle: 'Lunge di chuyển liên tục',
    description: 'Phát triển sức mạnh đùi và mông đồng thời cải thiện thăng bằng.',
    icon: Icons.directions_walk,
    primaryColor: const Color(0xFF9C27B0),
    secondaryColor: const Color(0xFF7B1FA2),
    difficulty: 'Trung bình',
    targetMuscles: const ['Đùi trước', 'Đùi sau', 'Mông'],
    duration: '20 reps',
    cameraHint: 'Quay ngang hông (Side View).',
    framingHint: 'Không gian cần rộng ít nhất 3m theo chiều ngang.',
    setupTips: const [
      'Đứng thẳng ở mép khung hình.',
      'Bước dài về phía trước, giữ thân người thẳng.',
    ],
    createExercise: () => WalkingLunge(),
    phaseColors: const { 'standing': Colors.grey, 'stepping': Colors.blue, 'descending': Colors.orange, 'bottom': Colors.green, 'pulling_through': Colors.purple },
  ),
  ExerciseDefinition(
    id: 'tricep_dip',
    name: 'Tricep Dip (Floor)',
    subtitle: 'Đẩy bắp tay sau trên sàn',
    description: 'Làm săn chắc bắp tay sau mà không cần dụng cụ.',
    icon: Icons.accessibility,
    primaryColor: const Color(0xFF00BCD4),
    secondaryColor: const Color(0xFF0097A7),
    difficulty: 'Cơ bản',
    targetMuscles: const ['Bắp tay sau', 'Vai', 'Ngực'],
    duration: '15 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Thấy rõ phần thân trên và góc khuỷu tay.',
    setupTips: const [
      'Ngồi trên sàn, tay chống phía sau lưng.',
      'Dùng tay đẩy hông lên, cánh tay thẳng.',
    ],
    createExercise: () => TricepDip(),
    phaseColors: const { 'setup_top': Colors.green, 'descending': Colors.orange, 'bottom': Colors.red, 'ascending': Colors.blue },
  ),
  ExerciseDefinition(
    id: 'pranamasana',
    name: 'Pranamasana',
    subtitle: 'Đứng cầu nguyện',
    description: 'Tư thế đứng cầu nguyện đầu tiên trong chuỗi Chào mặt trời.',
    icon: Icons.self_improvement,
    primaryColor: const Color(0xFF00E676),
    secondaryColor: const Color(0xFF00C853),
    difficulty: 'Cơ bản',
    targetMuscles: const ['Toàn thân'],
    duration: '5s hold',
    cameraHint: 'Quay ngang người hoặc chính diện.',
    framingHint: 'Đảm bảo thấy rõ thân trên đến đầu gối.',
    setupTips: const [
      'Đứng thẳng, chân chụm lại.',
      'Chắp hai tay trước ngực.',
      'Giữ yên trong 5 giây.',
    ],
    createExercise: () => Pranamasana(),
    phaseColors: const { 'setup': Colors.grey, 'holding': Colors.green },
  ),
  ExerciseDefinition(
    id: 'hasta_uttanasana',
    name: 'Hasta Uttanasana',
    subtitle: 'Vươn tay lên cao',
    description: 'Tư thế vươn người thứ hai trong chuỗi Chào mặt trời, kéo giãn cơ bụng và mở rộng lồng ngực.',
    icon: Icons.accessibility_new,
    primaryColor: const Color(0xFFFFD600),
    secondaryColor: const Color(0xFFFBC02D),
    difficulty: 'Cơ bản',
    targetMuscles: const ['Toàn thân', 'Cơ bụng', 'Lưng trên'],
    duration: '3s hold',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Đảm bảo thấy toàn bộ cơ thể từ đầu đến gót chân.',
    setupTips: const [
      'Hít vào, vươn hai tay lên cao qua đầu.',
      'Đẩy nhẹ hông về trước và ngả thân trên ra sau.',
      'Giữ yên trong 3 giây.',
    ],
    createExercise: () => HastaUttanasana(),
    phaseColors: const { 'setup': Colors.grey, 'holding': Colors.orange },
  ),
  ExerciseDefinition(
    id: 'hastapaadasana',
    name: 'Hastapaadasana',
    subtitle: 'Gập người chạm tay xuống đất',
    description: 'Tư thế thứ ba trong chuỗi Chào mặt trời, kéo giãn cơ gân kheo và lưng dưới.',
    icon: Icons.accessibility_new,
    primaryColor: const Color(0xFFFF9800),
    secondaryColor: const Color(0xFFF57C00),
    difficulty: 'Trung bình',
    targetMuscles: const ['Gân kheo', 'Lưng dưới', 'Mông'],
    duration: '1.5s hold',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Đảm bảo thấy toàn bộ cơ thể từ đầu đến gót chân.',
    setupTips: const [
      'Thở ra, gập người từ hông, giữ lưng thẳng.',
      'Hai tay chạm xuống sàn hoặc ôm lấy cổ chân.',
      'Cố gắng giữ chân thẳng, không gập gối quá nhiều.',
    ],
    createExercise: () => Hastapaadasana(),
    phaseColors: const { 'setup': Colors.grey, 'holding': Colors.orange },
  ),
  ExerciseDefinition(
    id: 'ashwa_sanchalanasana',
    name: 'Ashwa Sanchalanasana',
    subtitle: 'Tư thế kỵ sĩ',
    description: 'Tư thế thứ tư trong chuỗi Chào mặt trời, kéo giãn gân kheo chân sau và mở rộng khớp hông chân trước.',
    icon: Icons.directions_walk,
    primaryColor: const Color(0xFFFF6D00),
    secondaryColor: const Color(0xFFE65100),
    difficulty: 'Trung bình',
    targetMuscles: const ['Hông', 'Gân kheo', 'Đùi'],
    duration: '1.5s hold',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Đảm bảo thấy toàn bộ cơ thể từ đầu đến gót chân sau.',
    setupTips: const [
      'Từ tư thế cúi gập người, bước dài một chân ra sau.',
      'Hạ đầu gối chân sau xuống thảm, hạ thấp hông.',
      'Đầu gối chân trước vuông góc, vươn ngực và nhìn thẳng.',
    ],
    createExercise: () => AshwaSanchalanasana(),
    phaseColors: const { 'setup': Colors.grey, 'holding': Colors.orange },
  ),
  ExerciseDefinition(
    id: 'parvatasana',
    name: 'Parvatasana',
    subtitle: 'Chữ V ngược',
    description: 'Tư thế thứ năm trong chuỗi Chào mặt trời, tăng cường sức mạnh cánh tay và vai, kéo giãn lưng và gân kheo.',
    icon: Icons.change_history,
    primaryColor: const Color(0xFF673AB7),
    secondaryColor: const Color(0xFF512DA8),
    difficulty: 'Trung bình',
    targetMuscles: const ['Vai', 'Lưng', 'Gân kheo', 'Bắp chân'],
    duration: '1.5s hold',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Đảm bảo thấy toàn bộ cơ thể tạo thành hình chữ V ngược.',
    setupTips: const [
      'Từ tư thế kỵ sĩ, rút chân trước ra sau ngang với chân kia.',
      'Đẩy cao hông lên tạo thành chữ V ngược.',
      'Ép vai xuống, duỗi thẳng lưng, gót chân hướng về thảm.',
    ],
    createExercise: () => Parvatasana(),
    phaseColors: const { 'setup': Colors.grey, 'holding': Colors.deepPurple },
  ),
  ExerciseDefinition(
    id: 'ashtanga_namaskara',
    name: 'Ashtanga Namaskara',
    subtitle: 'Tư thế 8 điểm chạm sàn',
    description: 'Tư thế thứ sáu trong chuỗi Chào mặt trời, tăng cường sức mạnh cánh tay và vai, cải thiện sự linh hoạt của cột sống.',
    icon: Icons.accessibility,
    primaryColor: const Color(0xFFE91E63),
    secondaryColor: const Color(0xFFC2185B),
    difficulty: 'Trung bình',
    targetMuscles: const ['Vai', 'Cánh tay', 'Ngực', 'Core'],
    duration: '1.5s hold',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Đảm bảo thấy toàn bộ cơ thể tạo thành tư thế 8 điểm chạm sàn.',
    setupTips: const [
      'Từ tư thế chữ V ngược, hạ đầu gối xuống thảm.',
      'Hạ ngực và cằm xuống thảm, hông nhô cao.',
      'Khép chặt khuỷu tay vào sườn, không để bụng chạm thảm.',
    ],
    createExercise: () => AshtangaNamaskara(),
    phaseColors: const { 'setup': Colors.grey, 'holding': Colors.pink },
  ),
  ExerciseDefinition(
    id: 'russian_twist',
    name: 'Russian Twist',
    subtitle: 'Vặn mình kiểu Nga',
    description: 'Đánh tan mỡ eo và làm săn chắc cơ liên sườn.',
    icon: Icons.sync,
    primaryColor: const Color(0xFFFF5722),
    secondaryColor: const Color(0xFFE64A19),
    difficulty: 'Trung bình',
    targetMuscles: const ['Cơ liên sườn', 'Core', 'Bụng'],
    duration: '20 reps',
    cameraHint: 'Chính diện (Front View).',
    framingHint: 'Thấy rõ chuyển động của hai tay và hông.',
    setupTips: const [
      'Ngồi ngả người ra sau hình chữ V.',
      'Hai tay chụm lại trước ngực và vặn sang hai bên.',
    ],
    createExercise: () => RussianTwist(),
    phaseColors: const { 'center_setup': Colors.green, 'twisting': Colors.blue, 'max_point': Colors.orange, 'returning': Colors.purple },
  ),
  ExerciseDefinition(
    id: 'standing_knee_to_elbow',
    name: 'Standing Knee-to-Elbow',
    subtitle: 'Gối chạm khuỷu chéo góc',
    description: 'Cardio đứng vặn người, cải thiện sức bền và cơ chéo bụng.',
    icon: Icons.transfer_within_a_station,
    primaryColor: const Color(0xFF4CAF50),
    secondaryColor: const Color(0xFF388E3C),
    difficulty: 'Cơ bản',
    targetMuscles: const ['Core', 'Cơ liên sườn', 'Cardio'],
    duration: '30 reps',
    cameraHint: 'Quay chính diện (Front View).',
    framingHint: 'Thấy toàn bộ thân hình từ tay đến gót chân.',
    setupTips: const [
      'Đứng thẳng, hai tay sau gáy hoặc giơ cao.',
      'Kéo chéo đầu gối lên chạm khuỷu tay đối diện.',
    ],
    createExercise: () => StandingKneeToElbow(),
    phaseColors: const { 'standing_base': Colors.grey, 'approaching': Colors.blue, 'touch': Colors.green, 'returning': Colors.orange },
  ),
  ExerciseDefinition(
    id: 'jump_squat',
    name: 'Jump Squat',
    subtitle: 'Bật nhảy squat',
    description: 'Bài tập plyometric giúp tăng cường sức mạnh bùng nổ của cơ chân.',
    icon: Icons.fitness_center,
    primaryColor: const Color(0xFFF44336),
    secondaryColor: const Color(0xFFD32F2F),
    difficulty: 'Khó',
    targetMuscles: const ['Đùi trước', 'Mông', 'Bắp chân'],
    duration: '12 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Đảm bảo thấy toàn bộ cơ thể từ đầu đến chân khi bật cao.',
    setupTips: const [
      'Đứng thẳng, chân rộng bằng vai.',
      'Lấy đà và bật cao hết mức có thể.',
      'Tiếp đất mềm mại bằng mũi chân.'
    ],
    createExercise: () => JumpSquat(),
    phaseColors: const { 'standing': Colors.green, 'squatting': Colors.orange, 'launching': Colors.red, 'airborne': Colors.blue, 'landing': Colors.purple },
  ),
  ExerciseDefinition(
    id: 'bow_pose',
    name: 'Bow Pose',
    subtitle: 'Tư thế cánh cung',
    description: 'Mở rộng lồng ngực và kéo giãn mặt trước cơ thể.',
    icon: Icons.self_improvement,
    primaryColor: const Color(0xFF9C27B0),
    secondaryColor: const Color(0xFF7B1FA2),
    difficulty: 'Trung bình',
    targetMuscles: const ['Lưng', 'Ngực', 'Cột sống'],
    duration: '3 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Đảm bảo thấy toàn bộ cơ thể khi nằm.',
    setupTips: const [
      'Nằm sấp trên thảm.',
      'Gập hai gối, đưa tay ra sau nắm lấy cổ chân.',
      'Kéo lồng ngực và đùi lên khỏi mặt sàn.'
    ],
    createExercise: () => BowPose(),
    phaseColors: const { 'prone': Colors.grey, 'setup': Colors.blue, 'ascending': Colors.orange, 'hold': Colors.green, 'descending': Colors.red },
  ),
  ExerciseDefinition(
    id: 'side_plank_dip',
    name: 'Side Plank Dip',
    subtitle: 'Nâng hạ hông plank nghiêng',
    description: 'Làm săn chắc cơ liên sườn và tăng cường sức mạnh core.',
    icon: Icons.horizontal_rule,
    primaryColor: const Color(0xFF00BCD4),
    secondaryColor: const Color(0xFF0097A7),
    difficulty: 'Trung bình',
    targetMuscles: const ['Cơ liên sườn', 'Core', 'Vai'],
    duration: '12 reps',
    cameraHint: 'Quay chính diện (Front View) hoặc nghiêng nhẹ.',
    framingHint: 'Thấy rõ phần vai và hông.',
    setupTips: const [
      'Vào tư thế Side Plank trên khuỷu tay.',
      'Hạ hông xuống gần chạm sàn rồi nâng lên vị trí ban đầu.'
    ],
    createExercise: () => SidePlankDip(),
    phaseColors: const { 'basePlank': Colors.green, 'descending': Colors.orange, 'bottom': Colors.red, 'ascending': Colors.blue, 'top': Colors.purple },
  ),
  ExerciseDefinition(
    id: 'step_back_burpee',
    name: 'Step-Back Burpee',
    subtitle: 'Burpee bước lùi không nhảy',
    description: 'Bài tập toàn thân cardio thân thiện với khớp, không cần nhảy.',
    icon: Icons.directions_run,
    primaryColor: const Color(0xFFFF9800),
    secondaryColor: const Color(0xFFF57C00),
    difficulty: 'Trung bình',
    targetMuscles: const ['Toàn thân', 'Cardio', 'Core'],
    duration: '15 reps',
    cameraHint: 'Quay ngang người (Side View).',
    framingHint: 'Đảm bảo thấy toàn bộ cơ thể từ đầu đến chân.',
    setupTips: const [
      'Đứng thẳng, hạ người chống tay xuống thảm.',
      'Bước từng chân lùi về tư thế Plank, sau đó bước lên và đứng thẳng.'
    ],
    createExercise: () => StepBackBurpee(),
    phaseColors: const { 'standing': Colors.green, 'squattingDown': Colors.orange, 'steppingBack': Colors.blue, 'highPlank': Colors.red, 'steppingForward': Colors.purple, 'standingUp': Colors.cyan },
  ),
];
